AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'tmp/*'
    - 'vendor/*'
    - 'log/*'
    - 'node_modules/**/*'

Bundler/OrderedGems:
  Enabled: false

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'db/*'

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'db/*'

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'


Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/Lambda:
  Enabled: false
