AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'tmp/*'
    - 'vendor/*'
    - 'log/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'db/*'

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'db/*'

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/AlignHash:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
